from __future__ import annotations

import subprocess


class Publisher:
    def build_comment(self, title: str, video_path: str, duration_seconds: float) -> str:
        return (
            f"\U0001f3ac Video generated: {title}\n"
            f"Duration: {duration_seconds}s\n"
            f"{video_path}\n"
            "---\n"
            "Generated by VideoForge"
        )

    def post_pr_comment(self, pr_url: str, comment: str) -> dict:
        self._run_gh(["pr", "comment", pr_url, "--body", comment])
        return {"success": True}

    def _run_gh(self, args: list[str]) -> str:
        result = subprocess.run(["gh", *args], capture_output=True, text=True, check=True)
        return result.stdout
