import React from "react";
import { AbsoluteFill, useCurrentFrame, interpolate, spring, useVideoConfig, Easing } from "remotion";
import { z } from "zod";

export const OutroSceneSchema = z.object({
  title: z.string(),
  cta: z.string().optional(),
  duration: z.number().positive(),
});

export type OutroSceneProps = z.infer<typeof OutroSceneSchema>;

export const OutroScene: React.FC<OutroSceneProps> = ({ title, cta }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const cardSpring = spring({ frame, fps, config: { damping: 12, stiffness: 80 } });
  const cardOpacity = interpolate(frame, [0, 30], [0, 1], { extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const ctaOpacity = interpolate(frame, [20, 45], [0, 1], { extrapolateRight: "clamp" });
  const ctaSpring = spring({ frame: Math.max(0, frame - 20), fps, config: { damping: 10, stiffness: 120 } });
  const watermarkOpacity = interpolate(frame, [30, 50], [0, 0.3], { extrapolateRight: "clamp" });

  return (
    <AbsoluteFill style={{
      display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
      background: "linear-gradient(135deg, #0f0f23 0%, #1a1a3e 50%, #0a0a1a 100%)",
    }}>
      <div style={{
        opacity: cardOpacity,
        transform: `translateY(${(1 - cardSpring) * 40}px)`,
        display: "flex", flexDirection: "column", alignItems: "center",
      }}>
        <div style={{
          background: "rgba(255,255,255,0.06)",
          backdropFilter: "blur(2px)",
          borderRadius: 24,
          padding: "48px 64px",
          border: "1px solid rgba(255,255,255,0.08)",
          boxShadow: "none",
          textAlign: "center",
        }}>
          <div style={{
            fontSize: 40, fontWeight: "700", color: "#fff",
            letterSpacing: "-0.5px", marginBottom: 16,
          }}>
            {title}
          </div>
          <div style={{
            width: 60, height: 4, borderRadius: 2,
            background: "linear-gradient(90deg, #4a90d9, #7c5cbf)",
            margin: "0 auto",
          }} />
        </div>
      </div>

      {cta && (
        <div style={{
          opacity: ctaOpacity, marginTop: 40,
          transform: `scale(${ctaSpring})`,
        }}>
          <div style={{
            padding: "14px 36px",
            background: "linear-gradient(135deg, #4a90d9, #7c5cbf)",
            borderRadius: 12,
            boxShadow: "none",
            cursor: "pointer",
          }}>
            <span style={{ color: "#fff", fontSize: 18, fontWeight: "600", letterSpacing: 0.5 }}>
              {cta}
            </span>
          </div>
        </div>
      )}

      <div style={{
        position: "absolute", bottom: 40, opacity: watermarkOpacity,
        fontSize: 13, color: "rgba(255,255,255,0.2)", letterSpacing: 2,
      }}>
        GENERATED BY VIDEOFORGE
      </div>
    </AbsoluteFill>
  );
};
