import React from "react";
import { AbsoluteFill, useCurrentFrame, interpolate, spring, useVideoConfig, Easing } from "remotion";
import { z } from "zod";
import { colors, fonts, spacing } from "../design-tokens";

export const OutroSceneSchema = z.object({
  title: z.string(),
  cta: z.string().optional(),
  duration: z.number().positive(),
  wordTimestamps: z.array(z.object({ text: z.string(), startMs: z.number(), endMs: z.number() })).optional(),
  sceneStartFrame: z.number().optional().default(0),
});

export type OutroSceneProps = z.infer<typeof OutroSceneSchema>;

export const OutroScene: React.FC<OutroSceneProps> = ({ title, cta }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const cardSpring = spring({ frame, fps, config: { damping: 12, stiffness: 80 } });
  const cardOpacity = interpolate(frame, [0, 30], [0, 1], { extrapolateRight: "clamp", easing: Easing.out(Easing.cubic) });
  const ctaOpacity = interpolate(frame, [20, 45], [0, 1], { extrapolateRight: "clamp" });
  const ctaSpring = spring({ frame: Math.max(0, frame - 20), fps, config: { damping: 10, stiffness: 120 } });
  const watermarkOpacity = interpolate(frame, [30, 50], [0, 0.3], { extrapolateRight: "clamp" });

  return (
    <AbsoluteFill style={{
      display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
      background: colors.backgroundGradient,
    }}>
      <div style={{
        opacity: cardOpacity,
        transform: `translateY(${(1 - cardSpring) * 40}px)`,
        display: "flex", flexDirection: "column", alignItems: "center",
      }}>
        <div style={{
          background: colors.chromePanel,
          backdropFilter: "blur(2px)",
          borderRadius: 24,
          padding: `${spacing.xxl}px ${spacing.section}px`,
          border: `1px solid ${colors.chromeBorder}`,
          boxShadow: "none",
          textAlign: "center",
        }}>
          <div style={{
            fontSize: 40, fontWeight: "700", color: colors.text,
            letterSpacing: "-0.5px", marginBottom: spacing.md,
          }}>
            {title}
          </div>
          <div style={{
            width: 60, height: 4, borderRadius: 2,
            background: `linear-gradient(90deg, ${colors.primary}, ${colors.secondary})`,
            margin: "0 auto",
          }} />
        </div>
      </div>

      {cta && (
        <div style={{
          opacity: ctaOpacity, marginTop: 40,
          transform: `scale(${ctaSpring})`,
        }}>
          <div style={{
            padding: "14px 36px",
            background: `linear-gradient(135deg, ${colors.primary}, ${colors.secondary})`,
            borderRadius: 12,
            boxShadow: "none",
            cursor: "pointer",
          }}>
            <span style={{ color: colors.text, fontSize: 18, fontWeight: "600", letterSpacing: 0.5 }}>
              {cta}
            </span>
          </div>
        </div>
      )}

      <div style={{
        position: "absolute", bottom: 40, opacity: watermarkOpacity,
        fontSize: 13, color: colors.textMuted, letterSpacing: 2,
      }}>
        GENERATED BY VIDEOFORGE
      </div>
    </AbsoluteFill>
  );
};
