import React from "react";
import { useCurrentFrame } from "remotion";
import { z } from "zod";

export const OutroSceneSchema = z.object({
  title: z.string(),
  cta: z.string().optional(),
  duration: z.number().positive(),
});

export type OutroSceneProps = z.infer<typeof OutroSceneSchema>;

export const OutroScene: React.FC<OutroSceneProps> = ({
  title,
  cta,
}) => {
  const frame = useCurrentFrame();

  const titleOpacity = Math.min(1, frame / 30);
  const ctaOpacity = Math.min(1, (frame - 20) / 20);
  const watermarkOpacity = Math.min(1, (frame - 40) / 20);

  return (
    <div
      style={{
        flex: 1,
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#1a1a2e",
        width: "100%",
        height: "100%",
      }}
    >
      <div
        style={{
          opacity: titleOpacity,
          textAlign: "center",
          marginBottom: 24,
        }}
      >
        <div
          style={{
            fontSize: 48,
            fontWeight: "bold",
            color: "#fff",
            marginBottom: 16,
          }}
        >
          {title}
        </div>
      </div>

      {cta && (
        <div
          style={{
            opacity: ctaOpacity,
            padding: "14px 32px",
            backgroundColor: "#ffeb3b",
            borderRadius: 8,
            cursor: "pointer",
          }}
        >
          <span
            style={{
              color: "#1a1a2e",
              fontSize: 18,
              fontWeight: "bold",
            }}
          >
            {cta}
          </span>
        </div>
      )}

      <div
        style={{
          position: "absolute",
          bottom: 40,
          opacity: watermarkOpacity,
        }}
      >
        <span
          style={{
            color: "#555",
            fontSize: 14,
            letterSpacing: 1,
          }}
        >
          Generated by VideoForge
        </span>
      </div>
    </div>
  );
};
