/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DirectorPreviewRouteImport } from './routes/director-preview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as ReportsReportNameRouteImport } from './routes/reports/$reportName'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'

const DirectorPreviewRoute = DirectorPreviewRouteImport.update({
  id: '/director-preview',
  path: '/director-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportNameRoute = ReportsReportNameRouteImport.update({
  id: '/reports/$reportName',
  path: '/reports/$reportName',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/director-preview': typeof DirectorPreviewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/reports/$reportName': typeof ReportsReportNameRoute
  '/create/': typeof CreateIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/director-preview': typeof DirectorPreviewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/reports/$reportName': typeof ReportsReportNameRoute
  '/create': typeof CreateIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/director-preview': typeof DirectorPreviewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/reports/$reportName': typeof ReportsReportNameRoute
  '/create/': typeof CreateIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/director-preview'
    | '/jobs/$jobId'
    | '/reports/$reportName'
    | '/create/'
    | '/jobs/'
    | '/recipes/'
    | '/reports/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/director-preview'
    | '/jobs/$jobId'
    | '/reports/$reportName'
    | '/create'
    | '/jobs'
    | '/recipes'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/director-preview'
    | '/jobs/$jobId'
    | '/reports/$reportName'
    | '/create/'
    | '/jobs/'
    | '/recipes/'
    | '/reports/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectorPreviewRoute: typeof DirectorPreviewRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ReportsReportNameRoute: typeof ReportsReportNameRoute
  CreateIndexRoute: typeof CreateIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/director-preview': {
      id: '/director-preview'
      path: '/director-preview'
      fullPath: '/director-preview'
      preLoaderRoute: typeof DirectorPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportName': {
      id: '/reports/$reportName'
      path: '/reports/$reportName'
      fullPath: '/reports/$reportName'
      preLoaderRoute: typeof ReportsReportNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectorPreviewRoute: DirectorPreviewRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ReportsReportNameRoute: ReportsReportNameRoute,
  CreateIndexRoute: CreateIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
